### ISSUE TITLE
config module not available for py3.6

### ISSUE THREAD

**Issue by norlab** [whatismybrowser/api-v2-sample-code#1]
The python 3.6 code sample includes the use of the config module. It looks like the configparser module is an alternative but the code would need to be re-written. I would like to see an update to the code sample as I'm struggling to get it working.

**Comment by whatismybrowser** [comment]
Hi, all you need to do is make a copy of `config-dist.py` to `config.py` and put your API key in it.

`config.py` is git-ignored so that when you put your API key in it, git won't suggest that you commit the change.

I hope that helps!

**Comment by norlab** [comment]
Thank you for the quick response. I'm still a little confused. I'm running the code in a jupyter notebook. I've saved the config.py in the same folder as the .ipynb, but am not sure where to call it in the code. Is the `import config` argument no longer needed?

**Comment by whatismybrowser** [comment]
Ah ok great!

As long as you've got the python-requests module installed, that sample code should work then.

I haven't used Jupyter before but I'm working on some sample code for it to add to the collection.

let me know how you go :)

**Comment by norlab** [comment]
Any thoughts on why I get the following error:

ERROR: not a 200 result. instead got: 400.
{
  "result": {
    "message": "When doing batch processing, the user_agents key it must be a dictionary (key/value) type",
    "code": "error",
    "message_code": "invalid_user_agents_type"
  }
}
The API did not return a 'success' response. It said: result code: error, message_code: invalid_user_agents_type, message: When doing batch processing, the user_agents key it must be a dictionary (key/value) type
{
  "result": {
    "message": "When doing batch processing, the user_agents key it must be a dictionary (key/value) type",
    "code": "error",
    "message_code": "invalid_user_agents_type"
  }
}

My input looks like:
{"user_agents": {"0": "Opera/9.80 (SpreadTrum; Opera Mini/4.4.33961/75.35; U; fr) Presto/2.12.423 Version/12.16", "1": "Opera/9.80 (Android; Opera Mini/7.6.40125/66.247; U; fr) Presto/2.12.423 Version/12.16"}}

**Comment by whatismybrowser** [comment]
Closing this ticket as it was solved via email (json.dumps() was being called twice)
